console.log("HH   HH        lll lll                                  lll      dd !!! \nHH   HH   eee  lll lll  oooo   ww      ww  oooo  rr rr  lll      dd !!! \nHHHHHHH ee   e lll lll oo  oo  ww      ww oo  oo rrr  r lll  dddddd !!! \nHH   HH eeeee  lll lll oo  oo   ww ww ww  oo  oo rr     lll dd   dd     \nHH   HH  eeeee lll lll  oooo     ww  ww    oooo  rr     lll  dddddd !!!")
console.log("  ggggggggg    bbbbbbbbbbb")
console.log(" gg       gg   bb        bb")
console.log("gg             bb         bb" )
console.log("gg             bb        bb")
console.log("gg       gggg  bbbbbbbbbbb")
console.log("gg         gg  bb        bb")
console.log(" gg       gg   bb         bb")
console.log("  ggggggggg    bbbbbbbbbbbb")